CREATE TABLE IF NOT EXISTS stores (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(120) NOT NULL UNIQUE,
  logo TEXT NULL,
  primaryColor VARCHAR(20) NULL,
  secondaryColor VARCHAR(20) NULL,
  backgroundImage TEXT NULL,
  whatsappNumber VARCHAR(30) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  themeMode ENUM('LIGHT', 'DARK') NOT NULL DEFAULT 'DARK',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  storeId VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  INDEX idx_admin_store (storeId)
);

CREATE TABLE IF NOT EXISTS customers (
  id VARCHAR(36) PRIMARY KEY,
  storeId VARCHAR(36) NOT NULL,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(190) NULL,
  password VARCHAR(255) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  UNIQUE KEY uq_customer_store_phone (storeId, phone),
  INDEX idx_customer_store (storeId),
  INDEX idx_customer_store_email (storeId, email)
);

CREATE TABLE IF NOT EXISTS addresses (
  id VARCHAR(36) PRIMARY KEY,
  customerId VARCHAR(36) NOT NULL,
  fullName VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  addressLine1 VARCHAR(255) NOT NULL,
  addressLine2 VARCHAR(255) NULL,
  city VARCHAR(120) NOT NULL,
  state VARCHAR(120) NOT NULL,
  postalCode VARCHAR(20) NOT NULL,
  country VARCHAR(120) NOT NULL DEFAULT 'India',
  isDefault TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_address_customer FOREIGN KEY (customerId) REFERENCES customers(id) ON DELETE CASCADE,
  INDEX idx_address_customer (customerId)
);

CREATE TABLE IF NOT EXISTS settings (
  id VARCHAR(36) PRIMARY KEY,
  storeId VARCHAR(36) NOT NULL UNIQUE,
  keyName VARCHAR(100) NOT NULL,
  valueJson JSON NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_settings_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(36) PRIMARY KEY,
  storeId VARCHAR(36) NOT NULL,
  parentId VARCHAR(36) NULL,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(150) NULL,
  bannerImage TEXT NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_category_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_category_parent FOREIGN KEY (parentId) REFERENCES categories(id) ON DELETE SET NULL,
  INDEX idx_category_store (storeId),
  INDEX idx_category_parent (parentId),
  INDEX idx_category_sort (storeId, sortOrder)
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(36) PRIMARY KEY,
  storeId VARCHAR(36) NOT NULL,
  categoryId VARCHAR(36) NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT NULL,
  price DECIMAL(12, 2) NOT NULL,
  images JSON NULL,
  stock INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_category FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE RESTRICT,
  INDEX idx_product_store (storeId),
  INDEX idx_product_category (categoryId)
);

CREATE TABLE IF NOT EXISTS product_images (
  id VARCHAR(36) PRIMARY KEY,
  productId VARCHAR(36) NOT NULL,
  imageUrl TEXT NOT NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  isPrimary TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_images_product FOREIGN KEY (productId) REFERENCES products(id) ON DELETE CASCADE,
  INDEX idx_product_images_product (productId)
);

CREATE TABLE IF NOT EXISTS carts (
  id VARCHAR(36) PRIMARY KEY,
  customerId VARCHAR(36) NOT NULL,
  storeId VARCHAR(36) NOT NULL,
  status ENUM('ACTIVE', 'ORDERED', 'ABANDONED') NOT NULL DEFAULT 'ACTIVE',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cart_customer FOREIGN KEY (customerId) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  INDEX idx_cart_customer (customerId),
  INDEX idx_cart_store (storeId)
);

CREATE TABLE IF NOT EXISTS cart_items (
  id VARCHAR(36) PRIMARY KEY,
  cartId VARCHAR(36) NOT NULL,
  productId VARCHAR(36) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unitPrice DECIMAL(12, 2) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cart_item_cart FOREIGN KEY (cartId) REFERENCES carts(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_product FOREIGN KEY (productId) REFERENCES products(id) ON DELETE RESTRICT,
  UNIQUE KEY uq_cart_item_product (cartId, productId)
);

CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(36) PRIMARY KEY,
  storeId VARCHAR(36) NOT NULL,
  customerId VARCHAR(36) NOT NULL,
  totalAmount DECIMAL(12, 2) NOT NULL,
  shippingAmount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  shippingInfo JSON NULL,
  status ENUM('PLACED', 'CONFIRMED', 'PACKED', 'SHIPPED', 'DELIVERED') NOT NULL DEFAULT 'PLACED',
  paymentId VARCHAR(120) NULL,
  paymentStatus ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_store FOREIGN KEY (storeId) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_customer FOREIGN KEY (customerId) REFERENCES customers(id) ON DELETE RESTRICT,
  INDEX idx_order_store_created (storeId, createdAt),
  INDEX idx_order_customer (customerId),
  INDEX idx_order_status (status)
);

CREATE TABLE IF NOT EXISTS order_items (
  id VARCHAR(36) PRIMARY KEY,
  orderId VARCHAR(36) NOT NULL,
  productId VARCHAR(36) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(12, 2) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_item_order FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_item_product FOREIGN KEY (productId) REFERENCES products(id) ON DELETE RESTRICT,
  INDEX idx_order_item_order (orderId)
);

CREATE TABLE IF NOT EXISTS order_logs (
  id VARCHAR(36) PRIMARY KEY,
  orderId VARCHAR(36) NOT NULL,
  oldStatus VARCHAR(30) NULL,
  newStatus VARCHAR(30) NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_log_order FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_order_log_order (orderId)
);

CREATE TABLE IF NOT EXISTS payments (
  id VARCHAR(36) PRIMARY KEY,
  orderId VARCHAR(36) NOT NULL,
  provider ENUM('RAZORPAY', 'COD', 'OTHER') NOT NULL DEFAULT 'RAZORPAY',
  providerPaymentId VARCHAR(120) NULL,
  providerOrderId VARCHAR(120) NULL,
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  status ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING',
  rawResponse JSON NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_order FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_payment_order (orderId),
  INDEX idx_payment_status (status)
);

